const countryData = [
  { country: 'Worldwide', emoji: '🌏', index: 0 },
  { country: 'North America', emoji: '🏈', index: 1 },
  { country: 'Europe', emoji: '🇪🇺', index: 2 },
  { country: 'Latin America', emoji: '💃', index: 3 },
  { country: 'Asia', emoji: '⛩', index: 4 },
  { country: 'Africa', emoji: '🦁', index: 5 },
  { country: 'Oceania', emoji: '🌊', index: 6 },
  { country: 'Middle East', emoji: '🕌', index: 7 },
  { country: 'Afghanistan', emoji: '🇦🇫', index: 8 },
  { country: 'Albania', emoji: '🇦🇱', index: 9 },
  { country: 'Algeria', emoji: '🇩🇿', index: 10 },
  { country: 'American Samoa', emoji: '🇦🇸', index: 11 },
  { country: 'Andorra', emoji: '🇦🇩', index: 12 },
  { country: 'Angola', emoji: '🇦🇴', index: 13 },
  { country: 'Anguilla', emoji: '🇦🇮', index: 14 },
  { country: 'Antarctica', emoji: '🇦🇶', index: 15 },
  { country: 'Antigua and Barbuda', emoji: '🇦🇬', index: 16 },
  { country: 'Argentina', emoji: '🇦🇷', index: 17 },
  { country: 'Armenia', emoji: '🇦🇲', index: 18 },
  { country: 'Aruba', emoji: '🇦🇼', index: 19 },
  { country: 'Australia', emoji: '🇦🇺', index: 20 },
  { country: 'Austria', emoji: '🇦🇹', index: 21 },
  { country: 'Azerbaijan', emoji: '🇦🇿', index: 22 },
  { country: 'Bahamas', emoji: '🇧🇸', index: 23 },
  { country: 'Bahrain', emoji: '🇧🇭', index: 24 },
  { country: 'Bangladesh', emoji: '🇧🇩', index: 25 },
  { country: 'Barbados', emoji: '🇧🇧', index: 26 },
  { country: 'Belarus', emoji: '🇧🇾', index: 27 },
  { country: 'Bermuda', emoji: '🇧🇲', index: 28 },
  { country: 'Bhutan', emoji: '🇧🇹', index: 29 },
  { country: 'Bolivia', emoji: '🇧🇴', index: 30 },
  { country: 'Bosnia and Herzegovina', emoji: '🇧🇦', index: 31 },
  { country: 'Botswana', emoji: '🇧🇼', index: 32 },
  { country: 'Bouvet Island', emoji: '🇧🇻', index: 33 },
  { country: 'Brazil', emoji: '🇧🇷', index: 34 },
  { country: 'British Indian Ocean Territory', emoji: '🇮🇴', index: 35 },
  { country: 'British Virgin Islands', emoji: '🇻🇬', index: 36 },
  { country: 'Bulgaria', emoji: '🇧🇬', index: 37 },
  { country: 'Burkina Faso', emoji: '🇧🇫', index: 38 },
  { country: 'Cambodia', emoji: '🇰🇭', index: 39 },
  { country: 'Cameroon', emoji: '🇨🇲', index: 40 },
  { country: 'Canada', emoji: '🇨🇦', index: 41 },
  { country: 'Cape Verde', emoji: '🇨🇻', index: 42 },
  { country: 'Cayman Islands', emoji: '🇰🇾', index: 43 },
  { country: 'Central African Republic', emoji: '🇨🇫', index: 44 },
  { country: 'Chad', emoji: '🇹🇩', index: 45 },
  { country: 'China', emoji: '🇨🇳', index: 46 },
  { country: 'Christmas Island', emoji: '🇨🇽', index: 47 },
  { country: 'Cocos Islands', emoji: '🇨🇨', index: 48 },
  { country: 'Colombia', emoji: '🇨🇴', index: 49 },
  { country: 'Cook Islands', emoji: '🇨🇰', index: 50 },
  { country: 'Costa Rica', emoji: '🇨🇷', index: 51 },
  { country: 'Croatia', emoji: '🇭🇷', index: 52 },
  { country: 'Cuba', emoji: '🇨🇺', index: 53 },
  { country: 'Curacao', emoji: '🇨🇼', index: 54 },
  { country: 'Democratic Republic of the Congo', emoji: '🇨🇩', index: 55 },
  { country: 'Denmark', emoji: '🇩🇰', index: 56 },
  { country: 'Dominica', emoji: '🇩🇲', index: 57 },
  { country: 'Dominican Republic', emoji: '🇩🇴', index: 58 },
  { country: 'East Timor', emoji: '🇹🇱', index: 59 },
  { country: 'Ecuador', emoji: '🇪🇨', index: 60 },
  { country: 'El Salvador', emoji: '🇸🇻', index: 61 },
  { country: 'Equatorial Guinea', emoji: '🇬🇶', index: 62 },
  { country: 'Eritrea', emoji: '🇪🇷', index: 63 },
  { country: 'Estonia', emoji: '🇪🇪', index: 64 },
  { country: 'Ethiopia', emoji: '🇪🇹', index: 65 },
  { country: 'Falkland Islands', emoji: '🇫🇰', index: 66 },
  { country: 'Faroe Islands', emoji: '🇫🇴', index: 67 },
  { country: 'Finland', emoji: '🇫🇮', index: 68 },
  { country: 'France', emoji: '🇫🇷', index: 69 },
  { country: 'French Polynesia', emoji: '🇵🇫', index: 70 },
  { country: 'Gabon', emoji: '🇬🇦', index: 71 },
  { country: 'Gambia', emoji: '🇬🇲', index: 72 },
  { country: 'Georgia', emoji: '🇬🇪', index: 73 },
  { country: 'Germany', emoji: '🇩🇪', index: 74 },
  { country: 'Ghana', emoji: '🇬🇭', index: 75 },
  { country: 'Gibraltar', emoji: '🇬🇮', index: 76 },
  { country: 'Greenland', emoji: '🇬🇱', index: 77 },
  { country: 'Grenada', emoji: '🇬🇩', index: 78 },
  { country: 'Guam', emoji: '🇬🇺', index: 79 },
  { country: 'Guatemala', emoji: '🇬🇹', index: 80 },
  { country: 'Guinea', emoji: '🇬🇳', index: 81 },
  { country: 'Guinea-Bissau', emoji: '🇬🇼', index: 82 },
  { country: 'Bissau', emoji: '🇬🇼', index: 83 },
  { country: 'Guyana', emoji: '🇬🇾', index: 84 },
  { country: 'Haiti', emoji: '🇭🇹', index: 85 },
  { country: 'Heard Island and McDonald Islands', emoji: '🇭🇲', index: 86 },
  { country: 'Honduras', emoji: '🇭🇳', index: 87 },
  { country: 'Hungary', emoji: '🇭🇺', index: 88 },
  { country: 'Iceland', emoji: '🇮🇸', index: 89 },
  { country: 'India', emoji: '🇮🇳', index: 90 },
  { country: 'Indonesia', emoji: '🇮🇩', index: 91 },
  { country: 'Iran', emoji: '🇮🇷', index: 92 },
  { country: 'Iraq', emoji: '🇮🇶', index: 93 },
  { country: 'Ireland', emoji: '🇮🇪', index: 94 },
  { country: 'Isle of Man', emoji: '🇮🇲', index: 95 },
  { country: 'Israel', emoji: '🇮🇱', index: 96 },
  { country: 'Italy', emoji: '🇮🇹', index: 97 },
  { country: 'Ivory Coast', emoji: '🇨🇮', index: 98 },
  { country: 'Jamaica', emoji: '🇯🇲', index: 99 },
  { country: 'Japan', emoji: '🇯🇵', index: 100 },
  { country: 'Jordan', emoji: '🇯🇴', index: 101 },
  { country: 'Kazakhstan', emoji: '🇰🇿', index: 102 },
  { country: 'Kenya', emoji: '🇰🇪', index: 103 },
  { country: 'Kiribati', emoji: '🇰🇮', index: 104 },
  { country: 'Kuwait', emoji: '🇰🇼', index: 105 },
  { country: 'Kyrgyzstan', emoji: '🇰🇬', index: 106 },
  { country: 'Laos', emoji: '🇱🇦', index: 107 },
  { country: 'Latvia', emoji: '🇱🇻', index: 108 },
  { country: 'Lebanon', emoji: '🇱🇧', index: 109 },
  { country: 'Liberia', emoji: '🇱🇷', index: 110 },
  { country: 'Libya', emoji: '🇱🇾', index: 111 },
  { country: 'Lithuania', emoji: '🇱🇹', index: 112 },
  { country: 'Macau', emoji: '🇲🇴', index: 113 },
  { country: 'Macedonia', emoji: '🇲🇰', index: 114 },
  { country: 'Madagascar', emoji: '🇲🇬', index: 115 },
  { country: 'Malawi', emoji: '🇲🇼', index: 116 },
  { country: 'Malaysia', emoji: '🇲🇾', index: 117 },
  { country: 'Maldives', emoji: '🇲🇻', index: 118 },
  { country: 'Mali', emoji: '🇲🇱', index: 119 },
  { country: 'Malta', emoji: '🇲🇹', index: 120 },
  { country: 'Marshall Islands', emoji: '🇲🇭', index: 121 },
  { country: 'Mauritania', emoji: '🇲🇷', index: 122 },
  { country: 'Mauritius', emoji: '🇲🇺', index: 123 },
  { country: 'Mayotte', emoji: '🇾🇹', index: 124 },
  { country: 'Micronesia', emoji: '🇫🇲', index: 125 },
  { country: 'Moldova', emoji: '🇲🇩', index: 126 },
  { country: 'Monaco', emoji: '🇲🇨', index: 127 },
  { country: 'Mongolia', emoji: '🇲🇳', index: 128 },
  { country: 'Montserrat', emoji: '🇲🇸', index: 129 },
  { country: 'Mozambique', emoji: '🇲🇿', index: 130 },
  { country: 'Myanmar', emoji: '🇲🇲', index: 131 },
  { country: 'Namibia', emoji: '🇳🇦', index: 132 },
  { country: 'Nauru', emoji: '🇳🇷', index: 133 },
  { country: 'Nepal', emoji: '🇳🇵', index: 134 },
  { country: 'Netherlands', emoji: '🇳🇱', index: 135 },
  { country: 'Netherlands Antilles', emoji: '🇧🇶', index: 136 },
  { country: 'New Caledonia', emoji: '🇳🇨', index: 137 },
  { country: 'New Zealand', emoji: '🇳🇿', index: 138 },
  { country: 'Nicaragua', emoji: '🇳🇮', index: 139 },
  { country: 'Nigeria', emoji: '🇳🇬', index: 140 },
  { country: 'Norfolk Island', emoji: '🇳🇫', index: 141 },
  { country: 'North Korea', emoji: '🇰🇵', index: 142 },
  { country: 'Northern Mariana Islands', emoji: '🇲🇵', index: 143 },
  { country: 'Norway', emoji: '🇳🇴', index: 144 },
  { country: 'Oman', emoji: '🇴🇲', index: 145 },
  { country: 'Pakistan', emoji: '🇵🇰', index: 146 },
  { country: 'Palau', emoji: '🇵🇼', index: 147 },
  { country: 'Palestine', emoji: '🇵🇸', index: 148 },
  { country: 'Panama', emoji: '🇵🇦', index: 149 },
  { country: 'Papua New Guinea', emoji: '🇵🇬', index: 150 },
  { country: 'Paraguay', emoji: '🇵🇾', index: 151 },
  { country: 'Pitcairn', emoji: '🇵🇳', index: 152 },
  { country: 'Poland', emoji: '🇵🇱', index: 153 },
  { country: 'Portugal', emoji: '🇵🇹', index: 154 },
  { country: 'Qatar', emoji: '🇶🇦', index: 155 },
  { country: 'Romania', emoji: '🇷🇴', index: 156 },
  { country: 'Russia', emoji: '🇷🇺', index: 157 },
  { country: 'Rwanda', emoji: '🇷🇼', index: 158 },
  { country: 'Saint Barthelemy', emoji: '🇧🇱', index: 159 },
  { country: 'Saint Helena', emoji: '🇸🇭', index: 160 },
  { country: 'Saint Kitts and Nevis', emoji: '🇰🇳', index: 161 },
  { country: 'Saint Lucia', emoji: '🇱🇨', index: 162 },
  { country: 'Saint Martin', emoji: '🇲🇫', index: 163 },
  { country: 'Saint Pierre and Miquelon', emoji: '🇵🇲', index: 164 },
  { country: 'Saint Vincent and the Grenadines', emoji: '🇻🇨', index: 165 },
  { country: 'Samoa', emoji: '🇼🇸', index: 166 },
  { country: 'San Marino', emoji: '🇸🇲', index: 167 },
  { country: 'Sao Tome and Principe', emoji: '🇸🇹', index: 168 },
  { country: 'Saudi Arabia', emoji: '🇸🇦', index: 169 },
  { country: 'Senegal', emoji: '🇸🇳', index: 170 },
  { country: 'Serbia', emoji: '🇷🇸', index: 171 },
  { country: 'Sierra Leone', emoji: '🇸🇱', index: 172 },
  { country: 'Singapore', emoji: '🇸🇬', index: 173 },
  { country: 'Sint Maarten', emoji: '🇸🇽', index: 174 },
  { country: 'Slovakia', emoji: '🇸🇰', index: 175 },
  { country: 'Slovenia', emoji: '🇸🇮', index: 176 },
  { country: 'Solomon Islands', emoji: '🇸🇧', index: 177 },
  { country: 'Somalia', emoji: '🇸🇴', index: 178 },
  { country: 'South Africa', emoji: '🇿🇦', index: 179 },
  { country: 'South Georgia and the South Sandwich Islands', emoji: '🇬🇸', index: 180 },
  { country: 'South Korea', emoji: '🇰🇷', index: 181 },
  { country: 'South Sudan', emoji: '🇸🇸', index: 182 },
  { country: 'Spain', emoji: '🇪🇸', index: 183 },
  { country: 'Sri Lanka', emoji: '🇱🇰', index: 184 },
  { country: 'Sudan', emoji: '🇸🇩', index: 185 },
  { country: 'Suriname', emoji: '🇸🇷', index: 186 },
  { country: 'Svalbard and Jan Mayen', emoji: '🇸🇯', index: 187 },
  { country: 'Swaziland', emoji: '🇸🇿', index: 188 },
  { country: 'Switzerland', emoji: '🇨🇭', index: 189 },
  { country: 'Syria', emoji: '🇸🇾', index: 190 },
  { country: 'Taiwan', emoji: '🇹🇼', index: 191 },
  { country: 'Tajikistan', emoji: '🇹🇯', index: 192 },
  { country: 'Tanzania', emoji: '🇹🇿', index: 193 },
  { country: 'Thailand', emoji: '🇹🇭', index: 194 },
  { country: 'Tokelau', emoji: '🇹🇰', index: 195 },
  { country: 'Tonga', emoji: '🇹🇴', index: 196 },
  { country: 'Trinidad and Tobago', emoji: '🇹🇹', index: 197 },
  { country: 'Tunisia', emoji: '🇹🇳', index: 198 },
  { country: 'Turkmenistan', emoji: '🇹🇲', index: 199 },
  { country: 'Turks and Caicos Islands', emoji: '🇹🇨', index: 200 },
  { country: 'Tuvalu', emoji: '🇹🇻', index: 201 },
  { country: 'U.S. Virgin Islands', emoji: '🇻🇮', index: 202 },
  { country: 'Uganda', emoji: '🇺🇬', index: 203 },
  { country: 'Ukraine', emoji: '🇺🇦', index: 204 },
  { country: 'United Arab Emirates', emoji: '🇦🇪', index: 205 },
  { country: 'United States', emoji: '🇺🇸', index: 206 },
  { country: 'Los Angeles', emoji: '🇺🇸', index: 207 },
  { country: 'Chicago', emoji: '🇺🇸', index: 208 },
  { country: 'Philadelphia', emoji: '🇺🇸', index: 209 },
  { country: 'San Antonio', emoji: '🇺🇸', index: 210 },
  { country: 'San Diego', emoji: '🇺🇸', index: 211 },
  { country: 'Dallas', emoji: '🇺🇸', index: 212 },
  { country: 'San Jose', emoji: '🇺🇸', index: 213 },
  { country: 'San Diego Metro Area', emoji: '🇺🇸', index: 214 },
  { country: 'Austin', emoji: '🇺🇸', index: 215 },
  { country: 'Jacksonville', emoji: '🇺🇸', index: 216 },
  { country: 'San Francisco', emoji: '🇺🇸', index: 217 },
  { country: 'Charlotte', emoji: '🇺🇸', index: 218 },
  { country: 'Indianapolis', emoji: '🇺🇸', index: 219 },
  { country: 'Seattle', emoji: '🇺🇸', index: 220 },
  { country: 'Nashville', emoji: '🇺🇸', index: 221 },
  { country: 'El Paso', emoji: '🇺🇸', index: 222 },
  { country: 'Portland', emoji: '🇺🇸', index: 223 },
  { country: 'Oklahoma City', emoji: '🇺🇸', index: 224 },
  { country: 'Las Vegas', emoji: '🇺🇸', index: 225 },
  { country: 'Baltimore', emoji: '🇺🇸', index: 226 },
  { country: 'Milwaukee', emoji: '🇺🇸', index: 227 },
  { country: 'Albuquerque', emoji: '🇺🇸', index: 228 },
  { country: 'Sacramento', emoji: '🇺🇸', index: 229 },
  { country: 'Mesa', emoji: '🇺🇸', index: 230 },
  { country: 'Atlanta', emoji: '🇺🇸', index: 231 },
  { country: 'Kansas City', emoji: '🇺🇸', index: 232 },
  { country: 'Colorado Springs', emoji: '🇺🇸', index: 233 },
  { country: 'Miami', emoji: '🇺🇸', index: 234 },
  { country: 'Raleigh', emoji: '🇺🇸', index: 235 },
  { country: 'Omaha', emoji: '🇺🇸', index: 236 },
  { country: 'Long Beach', emoji: '🇺🇸', index: 237 },
  { country: 'Virginia Beach', emoji: '🇺🇸', index: 238 },
  { country: 'Oakland', emoji: '🇺🇸', index: 239 },
  { country: 'Minneapolis', emoji: '🇺🇸', index: 240 },
  { country: 'Tulsa', emoji: '🇺🇸', index: 241 },
  { country: 'Wichita', emoji: '🇺🇸', index: 242 },
  { country: 'New Orleans', emoji: '🇺🇸', index: 243 },
  { country: 'Arlington', emoji: '🇺🇸', index: 244 },
  { country: 'Tampa', emoji: '🇺🇸', index: 245 },
  { country: 'Santa Ana', emoji: '🇺🇸', index: 246 },
  { country: 'Santa Clara', emoji: '🇺🇸', index: 247 },
  { country: 'Cincinnati', emoji: '🇺🇸', index: 248 },
  { country: 'Anchorage', emoji: '🇺🇸', index: 249 },
  { country: 'Saint Paul', emoji: '🇺🇸', index: 250 },
  { country: 'Newark', emoji: '🇺🇸', index: 251 },
  { country: 'Buffalo', emoji: '🇺🇸', index: 252 },
  { country: 'Plano', emoji: '🇺🇸', index: 253 },
  { country: 'Fort Wayne', emoji: '🇺🇸', index: 254 },
  { country: 'Chula Vista', emoji: '🇺🇸', index: 255 },
  { country: 'Orlando', emoji: '🇺🇸', index: 256 },
  { country: 'Chandler', emoji: '🇺🇸', index: 257 },
  { country: 'Laredo', emoji: '🇺🇸', index: 258 },
  { country: 'Madison', emoji: '🇺🇸', index: 259 },
  { country: 'Winston-Salem', emoji: '🇺🇸', index: 260 },
  { country: 'Baton Rouge', emoji: '🇺🇸', index: 261 },
  { country: 'Durham', emoji: '🇺🇸', index: 262 },
  { country: 'Garland', emoji: '🇺🇸', index: 263 },
  { country: 'Glendale', emoji: '🇺🇸', index: 264 },
  { country: 'California', emoji: '🇺🇸', index: 265 },
  { country: 'Hialeah', emoji: '🇺🇸', index: 266 },
  { country: 'Chesapeake', emoji: '🇺🇸', index: 267 },
  { country: 'Scottsdale', emoji: '🇺🇸', index: 268 },
  { country: 'North Las Vegas', emoji: '🇺🇸', index: 269 },
  { country: 'Fayetteville', emoji: '🇺🇸', index: 270 },
  { country: 'Birmingham', emoji: '🇺🇸', index: 271 },
  { country: 'Oxnard', emoji: '🇺🇸', index: 272 },
  { country: 'Fontana', emoji: '🇺🇸', index: 273 },
  { country: 'Moreno Valley', emoji: '🇺🇸', index: 274 },
  { country: 'Huntington Beach', emoji: '🇺🇸', index: 275 },
  { country: 'Aurora', emoji: '🇺🇸', index: 276 },
  { country: 'Grand Rapids', emoji: '🇺🇸', index: 277 },
  { country: 'Salt Lake City', emoji: '🇺🇸', index: 278 },
  { country: 'Amarillo', emoji: '🇺🇸', index: 279 },
  { country: 'Akron', emoji: '🇺🇸', index: 280 },
  { country: 'Augusta', emoji: '🇺🇸', index: 281 },
  { country: 'Syracuse', emoji: '🇺🇸', index: 282 },
  { country: 'Jackson', emoji: '🇺🇸', index: 283 },
  { country: 'Cape Coral', emoji: '🇺🇸', index: 284 },
  { country: 'Grand Prairie', emoji: '🇺🇸', index: 285 },
  { country: 'East Los Angeles', emoji: '🇺🇸', index: 286 },
  { country: 'Peoria', emoji: '🇺🇸', index: 287 },
  { country: 'Cary', emoji: '🇺🇸', index: 288 },
  { country: 'Corona', emoji: '🇺🇸', index: 289 },
  { country: 'Salinas', emoji: '🇺🇸', index: 290 },
  { country: 'Palmdale', emoji: '🇺🇸', index: 291 },
  { country: 'Pasadena', emoji: '🇺🇸', index: 292 },
  { country: 'Fort Lauderdale', emoji: '🇺🇸', index: 293 },
  { country: 'Hayward', emoji: '🇺🇸', index: 294 },
  { country: 'Pomona', emoji: '🇺🇸', index: 295 },
  { country: 'Paterson', emoji: '🇺🇸', index: 296 },
  { country: 'Alexandria', emoji: '🇺🇸', index: 297 },
  { country: 'Sunnyvale', emoji: '🇺🇸', index: 298 },
  { country: 'Lakewood', emoji: '🇺🇸', index: 299 },
  { country: 'Torrance', emoji: '🇺🇸', index: 300 },
  { country: 'Clarksville', emoji: '🇺🇸', index: 301 },
  { country: 'Naperville', emoji: '🇺🇸', index: 302 },
  { country: 'Savannah', emoji: '🇺🇸', index: 303 },
  { country: 'McAllen', emoji: '🇺🇸', index: 304 },
  { country: 'Lancaster', emoji: '🇺🇸', index: 305 },
  { country: 'West Valley City', emoji: '🇺🇸', index: 306 },
  { country: 'Columbia', emoji: '🇺🇸', index: 307 },
  { country: 'Abilene', emoji: '🇺🇸', index: 308 },
  { country: 'Ann Arbor', emoji: '🇺🇸', index: 309 },
  { country: 'Allentown', emoji: '🇺🇸', index: 310 },
  { country: 'Beaumont', emoji: '🇺🇸', index: 311 },
  { country: 'Norman', emoji: '🇺🇸', index: 312 },
  { country: 'Costa Mesa', emoji: '🇺🇸', index: 313 },
  { country: 'San Buenaventura', emoji: '🇺🇸', index: 314 },
  { country: 'Miami Gardens', emoji: '🇺🇸', index: 315 },
  { country: 'Carlsbad', emoji: '🇺🇸', index: 316 },
  { country: 'North Charleston', emoji: '🇺🇸', index: 317 },
  { country: 'Fairfield', emoji: '🇺🇸', index: 318 },
  { country: 'Lafayette', emoji: '🇺🇸', index: 319 },
  { country: 'Gresham', emoji: '🇺🇸', index: 320 },
  { country: 'Missoula', emoji: '🇺🇸', index: 321 },
  { country: 'Gary', emoji: '🇺🇸', index: 322 },
  { country: 'West Covina', emoji: '🇺🇸', index: 323 },
  { country: 'La Mesa', emoji: '🇺🇸', index: 324 },
  { country: 'New Braunfels', emoji: '🇺🇸', index: 325 },
  { country: 'El Cajon', emoji: '🇺🇸', index: 326 },
  { country: 'Waltham', emoji: '🇺🇸', index: 327 },
  { country: 'Farmington', emoji: '🇺🇸', index: 328 },
  { country: 'Kahului', emoji: '🇺🇸', index: 329 },
  { country: 'Davenport', emoji: '🇺🇸', index: 330 },
  { country: 'San Juan', emoji: '🇺🇸', index: 331 },
  { country: 'South Pasadena', emoji: '🇺🇸', index: 332 },
  { country: 'Novato', emoji: '🇺🇸', index: 333 },
  { country: 'Richland', emoji: '🇺🇸', index: 334 },
  { country: 'La Quinta', emoji: '🇺🇸', index: 335 },
  { country: 'Machesney Park', emoji: '🇺🇸', index: 336 },
  { country: 'Floral Park', emoji: '🇺🇸', index: 337 },
  { country: 'South San Francisco', emoji: '🇺🇸', index: 338 },
  { country: 'Waupun', emoji: '🇺🇸', index: 339 },
  { country: 'Pleasant Grove', emoji: '🇺🇸', index: 340 },
  { country: 'Barnstable Town', emoji: '🇺🇸', index: 341 },
  { country: 'San Rafael', emoji: '🇺🇸', index: 342 },
  { country: 'Sun Village', emoji: '🇺🇸', index: 343 },
  { country: 'Rancho San Diego', emoji: '🇺🇸', index: 344 },
  { country: 'Falls Church', emoji: '🇺🇸', index: 345 },
  { country: 'North Adams', emoji: '🇺🇸', index: 346 },
  { country: 'Sallisaw', emoji: '🇺🇸', index: 347 },
  { country: 'Anaheim', emoji: '🇺🇸', index: 348 },
  { country: 'Palm Desert', emoji: '🇺🇸', index: 349 },
  { country: 'Lake Charles', emoji: '🇺🇸', index: 350 },
  { country: 'North Tonawanda', emoji: '🇺🇸', index: 351 },
  { country: 'Hastings', emoji: '🇺🇸', index: 352 },
  { country: 'Crawfordsville', emoji: '🇺🇸', index: 353 },
  { country: 'Camp Verde', emoji: '🇺🇸', index: 354 },
  { country: 'Dawson', emoji: '🇺🇸', index: 355 },
  { country: 'Madisonville', emoji: '🇺🇸', index: 356 },
  { country: 'Carrboro', emoji: '🇺🇸', index: 357 },
  { country: 'Mount Carmel', emoji: '🇺🇸', index: 358 },
  { country: 'Williamstown', emoji: '🇺🇸', index: 359 },
  { country: 'Marshall', emoji: '🇺🇸', index: 360 },
  { country: 'Elmwood Park', emoji: '🇺🇸', index: 361 },
  { country: 'Cherry Hills Village', emoji: '🇺🇸', index: 362 },
  { country: 'Cliffside Park', emoji: '🇺🇸', index: 363 },
  { country: 'Watsonville', emoji: '🇺🇸', index: 364 },
  { country: 'Matawan', emoji: '🇺🇸', index: 365 },
  { country: 'Lindale', emoji: '🇺🇸', index: 366 },
  { country: 'Albany', emoji: '🇺🇸', index: 367 },
  { country: 'Paso Robles', emoji: '🇺🇸', index: 368 },
  { country: 'Fort Thomas', emoji: '🇺🇸', index: 369 },
  { country: 'Dayton', emoji: '🇺🇸', index: 370 },
  { country: 'Washington DC', emoji: '🇺🇸', index: 371 },
  { country: 'Florida', emoji: '🇺🇸', index: 372 },
  { country: 'Texas', emoji: '🇺🇸', index: 373 },
  { country: 'Pennsylvania', emoji: '🇺🇸', index: 374 },
  { country: 'Hawaii', emoji: '🇺🇸', index: 375 },
  { country: 'Washington', emoji: '🇺🇸', index: 376 },
  { country: 'North Carolina', emoji: '🇺🇸', index: 377 },
  { country: 'Michigan', emoji: '🇺🇸', index: 378 },
  { country: 'Arizona', emoji: '🇺🇸', index: 379 },
  { country: 'Spokane', emoji: '🇺🇸', index: 380 },
  { country: 'San Bernardino', emoji: '🇺🇸', index: 381 },
  { country: 'Tacoma', emoji: '🇺🇸', index: 382 },
  { country: 'Des Moines', emoji: '🇺🇸', index: 383 },
  { country: 'Santa Clarita', emoji: '🇺🇸', index: 384 },
  { country: 'Uruguay', emoji: '🇺🇾', index: 385 },
  { country: 'Uzbekistan', emoji: '🇺🇿', index: 386 },
  { country: 'Vanuatu', emoji: '🇻🇺', index: 387 },
  { country: 'Vatican', emoji: '🇻🇦', index: 388 },
  { country: 'Venezuela', emoji: '🇻🇪', index: 389 },
  { country: 'Vietnam', emoji: '🇻🇳', index: 390 },
  { country: 'Wallis and Futuna', emoji: '🇼🇫', index: 391 },
  { country: 'Western Sahara', emoji: '🇪🇭', index: 392 },
  { country: 'Zambia', emoji: '🇿🇲', index: 393 },
  { country: 'Zimbabwe', emoji: '🇿🇼', index: 394 },
  { country: 'Alameda', emoji: '🇺🇸', index: 395 },
  { country: 'American Canyon', emoji: '🇺🇸', index: 396 },
  { country: 'Antioch', emoji: '🇺🇸', index: 397 },
  { country: 'Atherton', emoji: '🇺🇸', index: 398 },
  { country: 'Benicia', emoji: '🇺🇸', index: 399 },
  { country: 'Brisbane', emoji: '🇺🇸', index: 400 },
  { country: 'Burlingame', emoji: '🇺🇸', index: 401 },
  { country: 'Campbell', emoji: '🇺🇸', index: 402 },
  { country: 'Clayton', emoji: '🇺🇸', index: 403 },
  { country: 'Colma', emoji: '🇺🇸', index: 404 },
  { country: 'Corte Madera', emoji: '🇺🇸', index: 405 },
  { country: 'Daly City', emoji: '🇺🇸', index: 406 },
  { country: 'Danville', emoji: '🇺🇸', index: 407 },
  { country: 'East Palo Alto', emoji: '🇺🇸', index: 408 },
  { country: 'Fairfax', emoji: '🇺🇸', index: 409 },
  { country: 'Half Moon Bay', emoji: '🇺🇸', index: 410 },
  { country: 'Healdsburg', emoji: '🇺🇸', index: 411 },
  { country: 'Larkspur', emoji: '🇺🇸', index: 412 },
  { country: 'Los Altos', emoji: '🇺🇸', index: 413 },
  { country: 'Los Altos Hills', emoji: '🇺🇸', index: 414 },
  { country: 'Los Gatos', emoji: '🇺🇸', index: 415 },
  { country: 'Martinez', emoji: '🇺🇸', index: 416 },
  { country: 'Menlo Park', emoji: '🇺🇸', index: 417 },
  { country: 'Mill Valley', emoji: '🇺🇸', index: 418 },
  { country: 'Millbrae', emoji: '🇺🇸', index: 419 },
  { country: 'Milpitas', emoji: '🇺🇸', index: 420 },
  { country: 'Moraga', emoji: '🇺🇸', index: 421 },
  { country: 'Morgan Hill', emoji: '🇺🇸', index: 422 },
  { country: 'Mountain View', emoji: '🇺🇸', index: 423 },
  { country: 'Oakley', emoji: '🇺🇸', index: 424 },
  { country: 'Orinda', emoji: '🇺🇸', index: 425 },
  { country: 'Pacifica', emoji: '🇺🇸', index: 426 },
  { country: 'Palo Alto', emoji: '🇺🇸', index: 427 },
  { country: 'Petaluma', emoji: '🇺🇸', index: 428 },
  { country: 'Pleasanton', emoji: '🇺🇸', index: 429 },
  { country: 'Pleasant Hill', emoji: '🇺🇸', index: 430 },
  { country: 'Port Costa', emoji: '🇺🇸', index: 431 },
  { country: 'Rohnert Park', emoji: '🇺🇸', index: 432 },
  { country: 'Helena', emoji: '🇺🇸', index: 433 },
  { country: 'San Anselmo', emoji: '🇺🇸', index: 434 },
  { country: 'San Bruno', emoji: '🇺🇸', index: 435 },
  { country: 'San Carlos', emoji: '🇺🇸', index: 436 },
  { country: 'San Leandro', emoji: '🇺🇸', index: 437 },
  { country: 'San Mateo', emoji: '🇺🇸', index: 438 },
  { country: 'San Pablo', emoji: '🇺🇸', index: 439 },
  { country: 'San Ramon', emoji: '🇺🇸', index: 440 },
  { country: 'Santa Rosa', emoji: '🇺🇸', index: 441 },
  { country: 'Saratoga', emoji: '🇺🇸', index: 442 },
  { country: 'Sausalito', emoji: '🇺🇸', index: 443 },
  { country: 'Sebastopol', emoji: '🇺🇸', index: 444 },
  { country: 'Sonoma', emoji: '🇺🇸', index: 445 },
  { country: 'San Francisco Bay Area', emoji: '🇺🇸', index: 446 },
  { country: 'Vallejo', emoji: '🇺🇸', index: 447 },
  { country: 'Walnut Creek', emoji: '🇺🇸', index: 448 },
  { country: 'Kabul', emoji: '🇦🇫', index: 449 },
  { country: 'Algiers', emoji: '🇩🇿', index: 450 },
  { country: 'Luanda', emoji: '🇦🇴', index: 451 },
  { country: 'Buenos Aires', emoji: '🇦🇷', index: 452 },
  { country: 'Cordoba', emoji: '🇦🇷', index: 453 },
  { country: 'Rosario', emoji: '🇦🇷', index: 454 },
  { country: 'Mendoza', emoji: '🇦🇷', index: 455 },
  { country: 'Brisbane', emoji: '🇦🇺', index: 456 },
  { country: 'Adelaide', emoji: '🇦🇺', index: 457 },
  { country: 'Vienna', emoji: '🇦🇹', index: 458 },
  { country: 'Baku', emoji: '🇦🇿', index: 459 },
  { country: 'Dhaka', emoji: '🇧🇩', index: 460 },
  { country: 'Chittagong', emoji: '🇧🇩', index: 461 },
  { country: 'Abomey-Calavi', emoji: '🇧🇯', index: 462 },
  { country: 'La Paz', emoji: '🇧🇴', index: 463 },
  { country: 'Santa Cruz', emoji: '🇧🇴', index: 464 },
  { country: 'Cochabamba', emoji: '🇧🇴', index: 465 },
  { country: 'Sao Paulo', emoji: '🇧🇷', index: 466 },
  { country: 'Rio de Janeiro', emoji: '🇧🇷', index: 467 },
  { country: 'Brasilia', emoji: '🇧🇷', index: 468 },
  { country: 'Porto Alegre', emoji: '🇧🇷', index: 469 },
  { country: 'Fortaleza', emoji: '🇧🇷', index: 470 },
  { country: 'Salvador', emoji: '🇧🇷', index: 471 },
  { country: 'Curitiba', emoji: '🇧🇷', index: 472 },
  { country: 'Campinas', emoji: '🇧🇷', index: 473 },
  { country: 'Goiania', emoji: '🇧🇷', index: 474 },
  { country: 'Manaus', emoji: '🇧🇷', index: 475 },
  { country: 'Grande Vitoria', emoji: '🇧🇷', index: 476 },
  { country: 'Baixada Santista', emoji: '🇧🇷', index: 477 },
  { country: 'Natal', emoji: '🇧🇷', index: 478 },
  { country: 'Grande Sao Luis', emoji: '🇧🇷', index: 479 },
  { country: 'Joao Pessoa', emoji: '🇧🇷', index: 480 },
  { country: 'Maceio', emoji: '🇧🇷', index: 481 },
  { country: 'Florianopolis', emoji: '🇧🇷', index: 482 },
  { country: 'Sofia', emoji: '🇧🇬', index: 483 },
  { country: 'Ouagadougou', emoji: '🇧🇫', index: 484 },
  { country: 'Bujumbura', emoji: '🇧🇮', index: 485 },
  { country: 'Yaounde', emoji: '🇨🇲', index: 486 },
  { country: 'Douala', emoji: '🇨🇲', index: 487 },
  { country: 'Montreal', emoji: '🇨🇦', index: 488 },
  { country: 'Vancouver', emoji: '🇨🇦', index: 489 },
  { country: 'Calgary', emoji: '🇨🇦', index: 490 },
  { country: 'Ottawa', emoji: '🇨🇦', index: 491 },
  { country: 'N-Djamena', emoji: '🇹🇩', index: 492 },
  { country: 'Santiago', emoji: '🇨🇱', index: 493 },
  { country: 'Shanghai', emoji: '🇨🇳', index: 494 },
  { country: 'Tianjin', emoji: '🇨🇳', index: 495 },
  { country: 'Guangzhou', emoji: '🇨🇳', index: 496 },
  { country: 'Nanjing', emoji: '🇨🇳', index: 497 },
  { country: 'Wuhan', emoji: '🇨🇳', index: 498 },
  { country: 'Xi-an Shaanxi', emoji: '🇨🇳', index: 499 },
  { country: 'Hangzhou', emoji: '🇨🇳', index: 500 },

  { country: 'Shenyang', emoji: '🇨🇳', index: 501 },
  { country: 'Dongguan', emoji: '🇨🇳', index: 502 },
  { country: 'Foshan', emoji: '🇨🇳', index: 503 },
  { country: 'Haerbin', emoji: '🇨🇳', index: 504 },
  { country: 'Dalian', emoji: '🇨🇳', index: 505 },
  { country: 'Qingdao', emoji: '🇨🇳', index: 506 },
  { country: 'Ji-nan Shandong', emoji: '🇨🇳', index: 507 },
  { country: 'Changsha', emoji: '🇨🇳', index: 508 },
  { country: 'Changchun', emoji: '🇨🇳', index: 509 },
  { country: 'Shantou', emoji: '🇨🇳', index: 510 },
  { country: 'Shijiazhuang', emoji: '🇨🇳', index: 511 },
  { country: 'Nanning', emoji: '🇨🇳', index: 512 },
  { country: 'Taiyuan Shanxi', emoji: '🇨🇳', index: 513 },
  { country: 'Changzhou', emoji: '🇨🇳', index: 514 },
  { country: 'Xiamen', emoji: '🇨🇳', index: 515 },
  { country: 'Fuzhou Fujian', emoji: '🇨🇳', index: 516 },
  { country: 'Nanchang', emoji: '🇨🇳', index: 517 },
  { country: 'Tangshan Hebei', emoji: '🇨🇳', index: 518 },
  { country: 'Guiyang', emoji: '🇨🇳', index: 519 },
  { country: 'Lanzhou', emoji: '🇨🇳', index: 520 },
  { country: 'Zhongshan', emoji: '🇨🇳', index: 521 },
  { country: 'Handan', emoji: '🇨🇳', index: 522 },
  { country: 'Huaian', emoji: '🇨🇳', index: 523 },
  { country: 'Weifang', emoji: '🇨🇳', index: 524 },
  { country: 'Shaoxing', emoji: '🇨🇳', index: 525 },
  { country: 'Yantai', emoji: '🇨🇳', index: 526 },
  { country: 'Luoyang', emoji: '🇨🇳', index: 527 },
  { country: 'Nantong', emoji: '🇨🇳', index: 528 },
  { country: 'Baotou', emoji: '🇨🇳', index: 529 },
  { country: 'Putian', emoji: '🇨🇳', index: 530 },
  { country: 'Yangzhou', emoji: '🇨🇳', index: 531 },
  { country: 'Baoding', emoji: '🇨🇳', index: 532 },
  { country: 'Taizhou Zhejiang', emoji: '🇨🇳', index: 533 },
  { country: 'Wuhu Anhui', emoji: '🇨🇳', index: 534 },
  { country: 'Linyi Shandong', emoji: '🇨🇳', index: 535 },
  { country: 'Haikou', emoji: '🇨🇳', index: 536 },
  { country: 'Daqing', emoji: '🇨🇳', index: 537 },
  { country: 'Yancheng Jiangsu', emoji: '🇨🇳', index: 538 },
  { country: 'Lianyungang', emoji: '🇨🇳', index: 539 },
  { country: 'Zhuhai', emoji: '🇨🇳', index: 540 },
  { country: 'Datong', emoji: '🇨🇳', index: 541 },
  { country: 'Quanzhou', emoji: '🇨🇳', index: 542 },
  { country: 'Jiangmen', emoji: '🇨🇳', index: 543 },
  { country: 'Xiangyang', emoji: '🇨🇳', index: 544 },
  { country: 'Yinchuan', emoji: '🇨🇳', index: 545 },
  { country: 'Anshan', emoji: '🇨🇳', index: 546 },
  { country: 'Yichang', emoji: '🇨🇳', index: 547 },
  { country: 'Qinhuangdao', emoji: '🇨🇳', index: 548 },
  { country: 'Hengyang', emoji: '🇨🇳', index: 549 },
  { country: 'Qiqihaer', emoji: '🇨🇳', index: 550 },
  { country: 'Suqian', emoji: '🇨🇳', index: 551 },
  { country: 'Anyang', emoji: '🇨🇳', index: 552 },
  { country: 'Jining Shandong', emoji: '🇨🇳', index: 553 },
  { country: 'Zhangjiakou', emoji: '🇨🇳', index: 554 },
  { country: 'Huainan', emoji: '🇨🇳', index: 555 },
  { country: 'Chaozhou', emoji: '🇨🇳', index: 556 },
  { country: 'Taizhou Jiangsu', emoji: '🇨🇳', index: 557 },
  { country: 'Ganzhou', emoji: '🇨🇳', index: 558 },
  { country: 'Taian Shandong', emoji: '🇨🇳', index: 559 },
  { country: 'Weihai', emoji: '🇨🇳', index: 560 },
  { country: 'Jiaxing', emoji: '🇨🇳', index: 561 },
  { country: 'Kaifeng', emoji: '🇨🇳', index: 562 },
  { country: 'Rizhao', emoji: '🇨🇳', index: 563 },
  { country: 'Zhanjiang', emoji: '🇨🇳', index: 564 },
  { country: 'Nanchong', emoji: '🇨🇳', index: 565 },
  { country: 'Mianyang Sichuan', emoji: '🇨🇳', index: 566 },
  { country: 'Liuan', emoji: '🇨🇳', index: 567 },
  { country: 'Shiyan', emoji: '🇨🇳', index: 568 },
  { country: 'Liuyang', emoji: '🇨🇳', index: 569 },
  { country: 'Fushun Liaoning', emoji: '🇨🇳', index: 570 },
  { country: 'Maoming', emoji: '🇨🇳', index: 571 },
  { country: 'Ruian', emoji: '🇨🇳', index: 572 },
  { country: 'Jieyang', emoji: '🇨🇳', index: 573 },
  { country: 'Baoji', emoji: '🇨🇳', index: 574 },
  { country: 'Pingdingshan Henan', emoji: '🇨🇳', index: 575 },
  { country: 'Zhenjiang Jiangsu', emoji: '🇨🇳', index: 576 },
  { country: 'Jinhua', emoji: '🇨🇳', index: 577 },
  { country: 'Huaibei', emoji: '🇨🇳', index: 578 },
  { country: 'Nanyang Henan', emoji: '🇨🇳', index: 579 },
  { country: 'Xiangtan Hunan', emoji: '🇨🇳', index: 580 },
  { country: 'Liupanshui', emoji: '🇨🇳', index: 581 },
  { country: 'Xinxiang', emoji: '🇨🇳', index: 582 },
  { country: 'Bogota', emoji: '🇨🇴', index: 583 },
  { country: 'Cali', emoji: '🇨🇴', index: 584 },
  { country: 'Barranquilla', emoji: '🇨🇴', index: 585 },
  { country: 'Bucaramanga', emoji: '🇨🇴', index: 586 },
  { country: 'San Jose', emoji: '🇨🇷', index: 587 },
  { country: 'Havana', emoji: '🇨🇺', index: 588 },
  { country: 'Prague', emoji: '🇨🇿', index: 589 },
  { country: 'Copenhagen', emoji: '🇩🇰', index: 590 },
  { country: 'Santo Domingo', emoji: '🇩🇴', index: 591 },
  { country: 'Kinshasa', emoji: '🇨🇩', index: 592 },
  { country: 'Mbuji-Mayi', emoji: '🇨🇩', index: 593 },
  { country: 'Lubumbashi', emoji: '🇨🇩', index: 594 },
  { country: 'Kananga', emoji: '🇨🇩', index: 595 },
  { country: 'Kisangani', emoji: '🇨🇩', index: 596 },
  { country: 'Bukavu', emoji: '🇨🇩', index: 597 },
  { country: 'Guayaquil', emoji: '🇪🇨', index: 598 },
  { country: 'Cairo', emoji: '🇪🇬', index: 599 },
  { country: 'Alexandria', emoji: '🇪🇬', index: 600 },
  { country: 'Addis Ababa', emoji: '🇪🇹', index: 601 },
  { country: 'Paris', emoji: '🇫🇷', index: 602 },
  { country: 'Marseille', emoji: '🇫🇷', index: 603 },
  { country: 'Hamburg', emoji: 'de', index: 604 },
  { country: 'Kumasi', emoji: 'gh', index: 605 },
  { country: 'Accra', emoji: 'gh', index: 606 },
  { country: 'Athens', emoji: 'gr', index: 607 },
  { country: 'Guatemala City', emoji: 'gt', index: 608 },
  { country: 'Conakry', emoji: 'gn', index: 609 },
  { country: 'Port-au-Prince', emoji: 'ht', index: 610 },
  { country: 'Tegucigalpa', emoji: 'hn', index: 611 },
  { country: 'Budapest', emoji: 'hu', index: 612 },
  { country: 'Mumbai', emoji: 'in', index: 613 },
  { country: 'Kolkata', emoji: 'in', index: 614 },
  { country: 'Bangalore', emoji: 'in', index: 615 },
  { country: 'Chennai', emoji: 'in', index: 616 },
  { country: 'Hyderabad', emoji: 'in', index: 617 },
  { country: 'Ahmedabad', emoji: 'in', index: 618 },
  { country: 'Surat', emoji: 'in', index: 619 },
  { country: 'Jaipur', emoji: 'in', index: 620 },
  { country: 'Malappuram', emoji: 'in', index: 621 },
  { country: 'Kanpur', emoji: 'in', index: 622 },
  { country: 'Nagpur', emoji: 'in', index: 623 },
  { country: 'Coimbatore', emoji: 'in', index: 624 },
  { country: 'Thiruvananthapuram', emoji: 'in', index: 625 },
  { country: 'Patna', emoji: 'in', index: 626 },
  { country: 'Bhopal', emoji: 'in', index: 627 },
  { country: 'Agra', emoji: 'in', index: 628 },
  { country: 'Kannur', emoji: 'in', index: 629 },
  { country: 'Visakhapatnam', emoji: 'in', index: 630 },
  { country: 'Vadodara', emoji: 'in', index: 631 },
  { country: 'Nashik', emoji: 'in', index: 632 },
  { country: 'Vijayawada', emoji: 'in', index: 633 },
  { country: 'Kollam', emoji: 'in', index: 634 },
  { country: 'Rajkot', emoji: 'in', index: 635 },
  { country: 'Ludhiana', emoji: 'in', index: 636 },
  { country: 'Madurai', emoji: 'in', index: 637 },
  { country: 'Raipur', emoji: 'in', index: 638 },
  { country: 'Varanasi', emoji: 'in', index: 639 },
  { country: 'Jamshedpur', emoji: 'in', index: 640 },
  { country: 'Srinagar', emoji: 'in', index: 641 },
  { country: 'Aurangabad', emoji: 'in', index: 642 },
  { country: 'Ranchi', emoji: 'in', index: 643 },
  { country: 'Jabalpur', emoji: 'in', index: 644 },
  { country: 'Asansol', emoji: 'in', index: 645 },
  { country: 'Kota', emoji: 'in', index: 646 },
  { country: 'Gwalior', emoji: 'in', index: 647 },
  { country: 'Allahabad', emoji: 'in', index: 648 },
  { country: 'Amritsar', emoji: 'in', index: 649 },
  { country: 'Dhanbad', emoji: 'in', index: 650 },
  { country: 'Bareilly', emoji: 'in', index: 651 },
  { country: 'Aligarh', emoji: 'in', index: 652 },
  { country: 'Moradabad', emoji: 'in', index: 653 },
  { country: 'Durg-Bhilainagar', emoji: 'in', index: 654 },
  { country: 'Bhubaneswar', emoji: 'in', index: 655 },
  { country: 'Tiruchirappalli', emoji: 'in', index: 656 },
  { country: 'Chandigarh', emoji: 'in', index: 657 },
  { country: 'Hubli-Dharwad', emoji: 'in', index: 658 },
  { country: 'Guwahati', emoji: 'in', index: 659 },
  { country: 'Salem', emoji: 'in', index: 660 },
  { country: 'Saharanpur', emoji: 'in', index: 661 },
  { country: 'Jakarta', emoji: 'id', index: 662 },
  { country: 'Bekasi', emoji: 'id', index: 663 },
  { country: 'Surabaya', emoji: 'id', index: 664 },
  { country: 'Bandung', emoji: 'id', index: 665 },
  { country: 'Tangerang', emoji: 'id', index: 666 },
  { country: 'Medan', emoji: 'id', index: 667 },
  { country: 'Semarang', emoji: 'id', index: 668 },
  { country: 'Palembang', emoji: 'id', index: 669 },
  { country: 'Batam', emoji: 'id', index: 670 },
  { country: 'Makassar', emoji: 'id', index: 671 },
  { country: 'Pekan Baru', emoji: 'id', index: 672 },
  { country: 'Tasikmalaya', emoji: 'id', index: 673 },
  { country: 'Bandar Lampung', emoji: 'id', index: 674 },
  { country: 'Tehran', emoji: 'ir', index: 675 },
  { country: 'Mashhad', emoji: 'ir', index: 676 },
  { country: 'Esfahan', emoji: 'ir', index: 677 },
  { country: 'Shiraz', emoji: 'ir', index: 678 },
  { country: 'Tabriz', emoji: 'ir', index: 679 },
  { country: 'Karaj', emoji: 'ir', index: 680 },
  { country: 'Ahvaz', emoji: 'ir', index: 681 },
  { country: 'Baghdad', emoji: 'iq', index: 682 },
  { country: 'Basra', emoji: 'iq', index: 683 },
  { country: 'Tel Aviv', emoji: 'il', index: 684 },
  { country: 'Haifa', emoji: 'il', index: 685 },
  { country: 'Milan', emoji: 'it', index: 686 },
  { country: 'Naples', emoji: 'it', index: 687 },
  { country: 'Abidjan', emoji: 'ci', index: 688 },
  { country: 'Osaka', emoji: 'jp', index: 689 },
  { country: 'Nagoya', emoji: 'jp', index: 690 },
  { country: 'Fukuoka', emoji: 'jp', index: 691 },
  { country: 'Shizuoka', emoji: 'jp', index: 692 },
  { country: 'Sapporo', emoji: 'jp', index: 693 },
  { country: 'Sendai', emoji: 'jp', index: 694 },
  { country: 'Hiroshima', emoji: 'jp', index: 695 },
  { country: 'Amman', emoji: 'jo', index: 696 },
  { country: 'Almaty', emoji: 'kz', index: 697 },
  { country: 'Astana', emoji: 'kz', index: 698 },
  { country: 'Nairobi', emoji: 'ke', index: 699 },
  { country: 'Mombasa', emoji: 'ke', index: 700 },
  { country: 'Kuwait City', emoji: 'kw', index: 701 },
  { country: 'Monrovia', emoji: 'lr', index: 702 },
  { country: 'Antananarivo', emoji: 'mg', index: 703 },
  { country: 'Kuala Lumpur', emoji: 'my', index: 704 },
  { country: 'Bamako', emoji: 'ml', index: 705 },
  { country: 'Nouakchott', emoji: 'mr', index: 706 },
  { country: 'Guadalajara', emoji: 'mx', index: 707 },
  { country: 'Puebla', emoji: 'mx', index: 708 },
  { country: 'Toluca de Lerdo', emoji: 'mx', index: 709 },
  { country: 'Tijuana', emoji: 'mx', index: 710 },
  { country: 'Leon de los Aldamas', emoji: 'mx', index: 711 },
  { country: 'La Laguna', emoji: 'mx', index: 712 },
  { country: 'Ciudad Juarez', emoji: 'mx', index: 713 },
  { country: 'Queretaro', emoji: 'mx', index: 714 },
  { country: 'San Luis Potosi', emoji: 'mx', index: 715 },
  { country: 'Merida', emoji: 'mx', index: 716 },
  { country: 'Mexicali', emoji: 'mx', index: 717 },
  { country: 'Aguascalientes', emoji: 'mx', index: 718 },
  { country: 'Ulaanbaatar', emoji: 'mn', index: 719 },
  { country: 'Casablanca', emoji: 'ma', index: 720 },
  { country: 'Rabat', emoji: 'ma', index: 721 },
  { country: 'Tanger', emoji: 'ma', index: 722 },
  { country: 'Matola', emoji: 'mz', index: 723 },
  { country: 'Maputo', emoji: 'mz', index: 724 },
  { country: 'Yangon', emoji: 'mm', index: 725 },
  { country: 'Mandalay', emoji: 'mm', index: 726 },
  { country: 'Kathmandu', emoji: 'np', index: 727 },
  { country: 'Amsterdam', emoji: 'nl', index: 728 },
  { country: 'Auckland', emoji: 'nz', index: 729 },
  { country: 'Niamey', emoji: 'ne', index: 730 },

  { country: 'Lagos', emoji: 'ng', index: 731 },
  { country: 'Kano', emoji: 'ng', index: 732 },
  { country: 'Ibadan', emoji: 'ng', index: 733 },
  { country: 'Abuja', emoji: 'ng', index: 734 },
  { country: 'Port Harcourt', emoji: 'ng', index: 735 },
  { country: 'Onitsha', emoji: 'ng', index: 736 },
  { country: 'Kaduna', emoji: 'ng', index: 737 },
  { country: 'Aba', emoji: 'ng', index: 738 },
  { country: 'Pyongyang', emoji: 'kp', index: 739 },
  { country: 'Muscat', emoji: 'om', index: 740 },
  { country: 'Karachi', emoji: 'pk', index: 741 },
  { country: 'Lahore', emoji: 'pk', index: 742 },
  { country: 'Faisalabad', emoji: 'pk', index: 743 },
  { country: 'Gujranwala', emoji: 'pk', index: 744 },
  { country: 'Peshawar', emoji: 'pk', index: 745 },
  { country: 'Rawalpindi', emoji: 'pk', index: 746 },
  { country: 'Multan', emoji: 'pk', index: 747 },
  { country: 'Hyderabad', emoji: 'pk', index: 748 },
  { country: 'Islamabad', emoji: 'pk', index: 749 },
  { country: 'Quetta', emoji: 'pk', index: 750 },
  { country: 'Panama City', emoji: 'pa', index: 751 },
  { country: 'Asuncion', emoji: 'py', index: 752 },
  { country: 'Lima', emoji: 'pe', index: 753 },
  { country: 'Manila', emoji: 'ph', index: 754 },
  { country: 'Davao City', emoji: 'ph', index: 755 },
  { country: 'Warsaw', emoji: 'pl', index: 756 },
  { country: 'San Juan', emoji: 'pr', index: 757 },
  { country: 'Doha', emoji: 'qa', index: 758 },
  { country: 'Brazzaville', emoji: 'cg', index: 759 },
  { country: 'Bucharest', emoji: 'ro', index: 760 },
  { country: 'Saint Petersburg', emoji: 'ru', index: 761 },
  { country: 'Yekaterinburg', emoji: 'ru', index: 762 },
  { country: 'Kazan', emoji: 'ru', index: 763 },
  { country: 'Chelyabinsk', emoji: 'ru', index: 764 },
  { country: 'Krasnoyarsk', emoji: 'ru', index: 765 },
  { country: 'Samara', emoji: 'ru', index: 766 },
  { country: 'Ufa', emoji: 'ru', index: 767 },
  { country: 'Kigali', emoji: 'rw', index: 768 },
  { country: 'Riyadh', emoji: 'sa', index: 769 },
  { country: 'Jiddah', emoji: 'sa', index: 770 },
  { country: 'Mecca', emoji: 'sa', index: 771 },
  { country: 'Medina', emoji: 'sa', index: 772 },
  { country: 'Ad-Dammam', emoji: 'sa', index: 773 },
  { country: 'Dakar', emoji: 'sn', index: 774 },
  { country: 'Belgrade', emoji: 'rs', index: 775 },
  { country: 'Mogadishu', emoji: 'so', index: 776 },
  { country: 'Johannesburg', emoji: 'za', index: 777 },
  { country: 'Cape Town', emoji: 'za', index: 778 },
  { country: 'Durban', emoji: 'za', index: 779 },
  { country: 'Pretoria', emoji: 'za', index: 780 },
  { country: 'Port Elizabeth', emoji: 'za', index: 781 },
  { country: 'Busan', emoji: 'kr', index: 782 },
  { country: 'Daegu', emoji: 'kr', index: 783 },
  { country: 'Daejon', emoji: 'kr', index: 784 },
  { country: 'Gwangju', emoji: 'kr', index: 785 },
  { country: 'Madrid', emoji: 'es', index: 786 },
  { country: 'Barcelona', emoji: 'es', index: 787 },
  { country: 'Khartoum', emoji: 'sd', index: 788 },
  { country: 'Damascus', emoji: 'sy', index: 789 },
  { country: 'Aleppo', emoji: 'sy', index: 790 },
  { country: 'Taipei', emoji: 'tw', index: 791 },
  { country: 'Taoyuan', emoji: 'tw', index: 792 },
  { country: 'Gaoxiong', emoji: 'tw', index: 793 },
  { country: 'Taizhong', emoji: 'tw', index: 794 },
  { country: 'Dar es Salaam', emoji: 'tz', index: 795 },
  { country: 'Mwanza', emoji: 'tz', index: 796 },
  { country: 'Bangkok', emoji: 'th', index: 797 },
  { country: 'Samut Prakan', emoji: 'th', index: 798 },
  { country: 'Chiang Mai', emoji: 'th', index: 799 },
  { country: 'Istanbul', emoji: 'tr', index: 800 },

  { country: 'Ankara', emoji: '🇹🇷', index: 801 },
  { country: 'Bursa', emoji: '🇹🇷', index: 802 },
  { country: 'Adana', emoji: '🇹🇷', index: 803 },
  { country: 'Gaziantep', emoji: '🇹🇷', index: 804 },
  { country: 'Konya', emoji: '🇹🇷', index: 805 },
  { country: 'Antalya', emoji: '🇹🇷', index: 806 },
  { country: 'Kampala', emoji: '🇺🇬', index: 807 },
  { country: 'Kharkiv', emoji: '🇺🇦', index: 808 },
  { country: 'Dubai', emoji: '🇦🇪', index: 809 },
  { country: 'Sharjah', emoji: '🇦🇪', index: 810 },
  { country: 'Abu Dhabi', emoji: '🇦🇪', index: 811 },
  { country: 'Manchester', emoji: '🇬🇧', index: 812 },
  { country: 'Birmingham', emoji: '🇬🇧', index: 813 },
  { country: 'Glasgow', emoji: '🇬🇧', index: 814 },
  { country: 'Tashkent', emoji: '🇺🇿', index: 815 },
  { country: 'Caracas', emoji: '🇻🇪', index: 816 },
  { country: 'Maracaibo', emoji: '🇻🇪', index: 817 },
  { country: 'Valencia', emoji: '🇻🇪', index: 818 },
  { country: 'Barquisimeto', emoji: '🇻🇪', index: 819 },
  { country: 'Maracay', emoji: '🇻🇪', index: 820 },
  { country: 'Hanoi', emoji: '🇻🇳', index: 821 },
  { country: 'Can Tho', emoji: '🇻🇳', index: 822 },
  { country: 'Hai Phong', emoji: '🇻🇳', index: 823 },
  { country: 'Da Nang', emoji: '🇻🇳', index: 824 },
  { country: 'Sanaa', emoji: '🇾🇪', index: 825 },
  { country: 'Lusaka', emoji: '🇿🇲', index: 826 },
  { country: 'Harare', emoji: '🇿🇼', index: 827 },
  { country: 'Belgium', emoji: '🇧🇪', index: 828 },
  { country: 'Belize', emoji: '🇧🇿', index: 829 },
  { country: 'Benin', emoji: '🇧🇯', index: 830 },
  { country: 'Brunei', emoji: '🇧🇳', index: 831 },
  { country: 'Burundi', emoji: '🇧🇮', index: 832 },
  { country: 'Czech Republic', emoji: '🇨🇿', index: 833 },
  { country: 'Djibouti', emoji: '🇩🇯', index: 834 },
  { country: 'Luxembourg', emoji: '🇱🇺', index: 835 },
  { country: 'Republic of the Congo', emoji: '🇨🇬', index: 836 },
  { country: 'Columbus', emoji: '🇺🇸', index: 837 },
  { country: 'Boston', emoji: '🇺🇸', index: 838 },
  { country: 'Pittsburgh', emoji: '🇺🇸', index: 839 },
  { country: 'Greensboro', emoji: '🇺🇸', index: 840 },
  { country: 'St. Petersburg', emoji: '🇺🇸', index: 841 },
  { country: 'Lubbock', emoji: '🇺🇸', index: 842 },
  { country: 'Boise', emoji: '🇺🇸', index: 843 },
  { country: 'Boise City', emoji: '🇺🇸', index: 844 },
  { country: 'Brownsville', emoji: '🇺🇸', index: 845 },
  { country: 'Pembroke Pines', emoji: '🇺🇸', index: 846 },
  { country: 'Bridgeport', emoji: '🇺🇸', index: 847 },
  { country: 'Berkeley', emoji: '🇺🇸', index: 848 },
  { country: 'Billings', emoji: '🇺🇸', index: 849 },
  { country: 'Murfreesboro', emoji: '🇺🇸', index: 850 },
  { country: 'Bloomington', emoji: '🇺🇸', index: 851 },
  { country: 'Bellevue', emoji: '🇺🇸', index: 852 },
  { country: 'Greensburg', emoji: '🇺🇸', index: 853 },
  { country: 'Bedford', emoji: '🇺🇸', index: 854 },
  { country: 'Bridgeton', emoji: '🇺🇸', index: 855 },
  { country: 'Bucyrus', emoji: '🇺🇸', index: 856 },
  { country: 'Gibsonville', emoji: '🇺🇸', index: 857 },
  { country: 'Belmont', emoji: '🇺🇸', index: 858 },
  { country: 'Belvedere', emoji: '🇺🇸', index: 859 },
  { country: 'Dublin', emoji: '🇺🇸', index: 860 },
  { country: 'Hillsborough', emoji: '🇺🇸', index: 861 },
  { country: 'Pittsburg', emoji: '🇺🇸', index: 862 },
  { country: 'Tiburon', emoji: '🇺🇸', index: 863 },
  { country: 'Melbourne', emoji: '🇦🇺', index: 864 },
  { country: 'Brussels', emoji: '🇧🇪', index: 865 },
  { country: 'Belo Horizonte', emoji: '🇧🇷', index: 866 },
  { country: 'Belem', emoji: '🇧🇷', index: 867 },
  { country: 'Beijing', emoji: '🇨🇳', index: 868 },
  { country: 'Ningbo', emoji: '🇨🇳', index: 869 },
  { country: 'Zibo', emoji: '🇨🇳', index: 870 },
  { country: 'Benxi', emoji: '🇨🇳', index: 871 },
  { country: 'Binzhou', emoji: '🇨🇳', index: 872 },
  { country: 'Berlin', emoji: '🇩🇪', index: 873 },
  { country: 'Bogor', emoji: '🇮🇩', index: 874 },
  { country: 'Dublin', emoji: '🇮🇪', index: 875 },
  { country: 'Beirut', emoji: '🇱🇧', index: 876 },
  { country: 'Benin City', emoji: '🇳🇬', index: 877 },
  { country: 'Lisbon', emoji: '🇵🇹', index: 878 },
  { country: 'Novosibirsk', emoji: '🇷🇺', index: 879 },
  { country: 'Xinbei', emoji: '🇹🇼', index: 880 },
  { country: 'Chon Buri', emoji: '🇹🇭', index: 881 },
  { country: 'Chile', emoji: '🇨🇱', index: 882 },
  { country: 'Comoros', emoji: '🇰🇲', index: 883 },
  { country: 'Cyprus', emoji: '🇨🇾', index: 884 },
  { country: 'French Southern Territories', emoji: '🇹🇫', index: 885 },
  { country: 'Greece', emoji: '🇬🇷', index: 886 },
  { country: 'Liechtenstein', emoji: '🇱🇮', index: 887 },
  { country: 'Mexico', emoji: '🇲🇽', index: 888 },
  { country: 'Morocco', emoji: '🇲🇦', index: 889 },
  { country: 'Puerto Rico', emoji: '🇵🇷', index: 890 },
  { country: 'Seychelles', emoji: '🇸🇨', index: 891 },
  { country: 'New York City', emoji: '🇺🇸', index: 892 },
  { country: 'Tucson', emoji: '🇺🇸', index: 893 },
  { country: 'Corpus Christi', emoji: '🇺🇸', index: 894 },
  { country: 'Stockton', emoji: '🇺🇸', index: 895 },
  { country: 'Lincoln', emoji: '🇺🇸', index: 896 },
  { country: 'Jersey City', emoji: '🇺🇸', index: 897 },
  { country: 'Rochester', emoji: '🇺🇸', index: 898 },
  { country: 'Little Rock', emoji: '🇺🇸', index: 899 },
  { country: 'Port St. Lucie', emoji: '🇺🇸', index: 900 },
  { country: 'Fort Collins', emoji: '🇺🇸', index: 901 },
  { country: 'Escondido', emoji: '🇺🇸', index: 902 },
  { country: 'Rockford', emoji: '🇺🇸', index: 903 },
  { country: 'Frisco', emoji: '🇺🇸', index: 904 },
  { country: 'McKinney', emoji: '🇺🇸', index: 905 },
  { country: 'Independence', emoji: '🇺🇸', index: 906 },
  { country: 'Round Rock', emoji: '🇺🇸', index: 907 },
  { country: 'St. Cloud', emoji: '🇺🇸', index: 908 },
  { country: 'Lompoc', emoji: '🇺🇸', index: 909 },
  { country: 'Chillicothe', emoji: '🇺🇸', index: 910 },
  { country: 'Hercules', emoji: '🇺🇸', index: 911 },
  { country: 'El Cerrito', emoji: '🇺🇸', index: 912 },
  { country: 'Crestview', emoji: '🇺🇸', index: 913 },
  { country: 'Cresskill', emoji: '🇺🇸', index: 914 },
  { country: 'Crestwood', emoji: '🇺🇸', index: 915 },
  { country: 'Concord', emoji: '🇺🇸', index: 916 },
  { country: 'Cupertino', emoji: '🇺🇸', index: 917 },
  { country: 'Foster City', emoji: '🇺🇸', index: 918 },
  { country: 'Redwood City', emoji: '🇺🇸', index: 919 },
  { country: 'Richmond', emoji: '🇺🇸', index: 920 },
  { country: 'Suisun City', emoji: '🇺🇸', index: 921 },
  { country: 'Union City', emoji: '🇺🇸', index: 922 },
  { country: 'Recife', emoji: '🇧🇷', index: 923 },
  { country: 'Chongqing', emoji: '🇨🇳', index: 924 },
  { country: 'Chengdu', emoji: '🇨🇳', index: 925 },
  { country: 'Cixi', emoji: '🇨🇳', index: 926 },
  { country: 'Chifeng', emoji: '🇨🇳', index: 927 },
  { country: 'Munich', emoji: '🇩🇪', index: 928 },
  { country: 'Cologne', emoji: '🇩🇪', index: 929 },
  { country: 'Lucknow', emoji: '🇮🇳', index: 930 },

  { country: 'Kochi', emoji: '🇮🇳', index: 931 },
  { country: 'Mexico City', emoji: '🇲🇽', index: 932 },
  { country: 'Moscow', emoji: '🇷🇺', index: 933 },
  { country: 'Incheon', emoji: '🇰🇷', index: 934 },
  { country: 'Stockholm', emoji: '🇸🇪', index: 935 },
  { country: 'Zurich', emoji: '🇨🇭', index: 936 },
  { country: 'Ho Chi Minh City', emoji: '🇻🇳', index: 937 },
  { country: 'Sweden', emoji: '🇸🇪', index: 938 },
  { country: 'United Kingdom', emoji: '🇬🇧', index: 939 },
  { country: 'Denver', emoji: '🇺🇸', index: 940 },
  { country: 'Detroit', emoji: '🇺🇸', index: 941 },
  { country: 'Riverside', emoji: '🇺🇸', index: 942 },
  { country: 'Toledo', emoji: '🇺🇸', index: 943 },
  { country: 'Henderson', emoji: '🇺🇸', index: 944 },
  { country: 'Modesto', emoji: '🇺🇸', index: 945 },
  { country: 'Springfield', emoji: '🇺🇸', index: 946 },
  { country: 'Hollywood', emoji: '🇺🇸', index: 947 },
  { country: 'Downey', emoji: '🇺🇸', index: 948 },
  { country: 'Inglewood', emoji: '🇺🇸', index: 949 },
  { country: 'Duluth', emoji: '🇺🇸', index: 950 },
  { country: 'Enid', emoji: '🇺🇸', index: 951 },
  { country: 'Kirkwood', emoji: '🇺🇸', index: 952 },
  { country: 'Golden', emoji: '🇺🇸', index: 953 },
  { country: 'Ridgefield', emoji: '🇺🇸', index: 954 },
  { country: 'Fridley', emoji: '🇺🇸', index: 955 },
  { country: 'Grosse Pointe Woods', emoji: '🇺🇸', index: 956 },
  { country: 'Piedmont', emoji: '🇺🇸', index: 957 },
  { country: 'Windsor', emoji: '🇺🇸', index: 958 },
  { country: 'Woodside', emoji: '🇺🇸', index: 959 },
  { country: 'Sydney', emoji: '🇦🇺', index: 960 },
  { country: 'Edmonton', emoji: '🇨🇦', index: 961 },
  { country: 'Dongying', emoji: '🇨🇳', index: 962 },
  { country: 'Medellin', emoji: '🇨🇴', index: 963 },
  { country: 'Delhi', emoji: '🇮🇳', index: 964 },
  { country: 'New Delhi', emoji: '🇮🇳', index: 965 },
  { country: 'Kozhikode', emoji: '🇮🇳', index: 966 },
  { country: 'Indore', emoji: '🇮🇳', index: 967 },
  { country: 'Jodhpur', emoji: '🇮🇳', index: 968 },
  { country: 'Depok', emoji: '🇮🇩', index: 969 },
  { country: 'Nizhniy Novgorod', emoji: '🇷🇺', index: 970 },
  { country: 'Rostov-on-Don', emoji: '🇷🇺', index: 971 },
  { country: 'London', emoji: '🇬🇧', index: 972 },
  { country: 'Montevideo', emoji: '🇺🇾', index: 973 },
  { country: 'Egypt', emoji: '🇪🇬', index: 974 },
  { country: 'Guernsey', emoji: '🇬🇬', index: 975 },
  { country: 'Jersey', emoji: '🇯🇪', index: 976 },
  { country: 'Lesotho', emoji: '🇱🇸', index: 977 },
  { country: 'Montenegro', emoji: '🇲🇪', index: 978 },
  { country: 'Niger', emoji: '🇳🇪', index: 979 },
  { country: 'Niue', emoji: '🇳🇺', index: 980 },
  { country: 'Peru', emoji: '🇵🇪', index: 981 },
  { country: 'Philippines', emoji: '🇵🇭', index: 982 },
  { country: 'Reunion', emoji: '🇷🇪', index: 983 },
  { country: 'Turkey', emoji: '🇹🇷', index: 984 },
  { country: 'New York', emoji: '🇺🇸', index: 985 },
  { country: 'Phoenix', emoji: '🇺🇸', index: 986 },
  { country: 'Memphis', emoji: '🇺🇸', index: 987 },
  { country: 'Louisville', emoji: '🇺🇸', index: 988 },
  { country: 'Fresno', emoji: '🇺🇸', index: 989 },
  { country: 'Lexington', emoji: '🇺🇸', index: 990 },
  { country: 'Reno', emoji: '🇺🇸', index: 991 },
  { country: 'Fremont', emoji: '🇺🇸', index: 992 },
  { country: 'Irvine', emoji: '🇺🇸', index: 993 },
  { country: 'Yonkers', emoji: '🇺🇸', index: 994 },
  { country: 'Montgomery', emoji: '🇺🇸', index: 995 },
  { country: 'Huntsville', emoji: '🇺🇸', index: 996 },
  { country: 'Tempe', emoji: '🇺🇸', index: 997 },
  { country: 'Elk Grove', emoji: '🇺🇸', index: 998 },
  { country: 'Joliet', emoji: '🇺🇸', index: 999 },
  { country: 'Mesquite', emoji: '🇺🇸', index: 1000 },
  { country: 'Westminster', emoji: '🇺🇸', index: 1001 },
  { country: 'Glenview', emoji: '🇺🇸', index: 1002 },
  { country: 'Perris', emoji: '🇺🇸', index: 1003 },
  { country: 'Gloversville', emoji: '🇺🇸', index: 1004 },
  { country: 'Merrillville', emoji: '🇺🇸', index: 1005 },
  { country: 'Lewistown', emoji: '🇺🇸', index: 1006 },
  { country: 'River Grove', emoji: '🇺🇸', index: 1007 },
  { country: 'Green River', emoji: '🇺🇸', index: 1008 },
  { country: 'Progreso', emoji: '🇺🇸', index: 1009 },
  { country: 'Yemen', emoji: '🇾🇪', index: 1010 },
  { country: 'Emeryville', emoji: '🇺🇸', index: 1011 },
  { country: 'Livermore', emoji: '🇺🇸', index: 1012 },
  { country: 'Pinole', emoji: '🇺🇸', index: 1013 },
  { country: 'Perth', emoji: '🇦🇺', index: 1014 },
  { country: 'Joinville', emoji: '🇧🇷', index: 1015 },
  { country: 'Phnom Penh', emoji: '🇰🇭', index: 1016 },
  { country: 'Shenzhen', emoji: '🇨🇳', index: 1017 },
  { country: 'Zhengzhou', emoji: '🇨🇳', index: 1018 },
  { country: 'Hefei', emoji: '🇨🇳', index: 1019 },
  { country: 'Wenzhou', emoji: '🇨🇳', index: 1020 },
  { country: 'Tengzhou', emoji: '🇨🇳', index: 1021 },
  { country: 'Luohe', emoji: '🇨🇳', index: 1022 },
  { country: 'Yueqing', emoji: '🇨🇳', index: 1023 },
  { country: 'Helsinki', emoji: '🇫🇮', index: 1024 },
  { country: 'Pune', emoji: '🇮🇳', index: 1025 },
  { country: 'Meerut', emoji: '🇮🇳', index: 1026 },
  { country: 'Mysore', emoji: '🇮🇳', index: 1027 },
  { country: 'Rome', emoji: '🇮🇹', index: 1028 },
  { country: 'Shimkent', emoji: '🇰🇿', index: 1029 },
  { country: 'Lilongwe', emoji: '🇲🇼', index: 1030 },
  { country: 'Monterrey', emoji: '🇲🇽', index: 1031 },
  { country: 'Fes', emoji: '🇲🇦', index: 1032 },
  { country: 'Nnewi', emoji: '🇳🇬', index: 1033 },
  { country: 'Pointe-Noire', emoji: '🇨🇬', index: 1034 },
  { country: 'Freetown', emoji: '🇸🇱', index: 1035 },
  { country: 'Ekurhuleni', emoji: '🇿🇦', index: 1036 },
  { country: 'Seoul', emoji: '🇰🇷', index: 1037 },
  { country: 'Suweon', emoji: '🇰🇷', index: 1038 },
  { country: 'Lome', emoji: '🇹🇬', index: 1039 },
  { country: 'Kiev', emoji: '🇺🇦', index: 1040 },
  { country: 'West Yorkshire', emoji: '🇬🇧', index: 1041 },
  { country: 'Fiji', emoji: '🇫🇯', index: 1042 },
  { country: 'Fort Worth', emoji: '🇺🇸', index: 1043 },
  { country: 'Norfolk', emoji: '🇺🇸', index: 1044 },
  { country: 'Fulton', emoji: '🇺🇸', index: 1045 },
  { country: 'Togo', emoji: '🇹🇬', index: 1046 },
  { country: 'Irving', emoji: '🇺🇸', index: 1047 },
  { country: 'Gilroy', emoji: '🇺🇸', index: 1048 },
  { country: 'Kunming', emoji: '🇨🇳', index: 1049 },
  { country: 'Xining', emoji: '🇨🇳', index: 1050 },

  { country: 'Yingkou', emoji: '🇨🇳', index: 1051 },
  { country: 'Puning', emoji: '🇨🇳', index: 1052 },
  { country: 'Guilin', emoji: '🇨🇳', index: 1053 },
  { country: 'Hong Kong', emoji: '🇭🇰', index: 1054 },
  { country: 'Kingston', emoji: '🇯🇲', index: 1055 },
  { country: 'Yongin', emoji: '🇰🇷', index: 1056 },
  { country: 'Houston', emoji: '🇺🇸', index: 1057 },
  { country: 'Northport', emoji: '🇺🇸', index: 1058 },
  { country: 'Ohio', emoji: '🇺🇸', index: 1059 },
  { country: 'Honolulu, HI', emoji: '🇺🇸', index: 1060 },
  { country: 'Suzhou', emoji: '🇨🇳', index: 1061 },
  { country: 'Huizhou', emoji: '🇨🇳', index: 1062 },
  { country: 'Hohhot', emoji: '🇨🇳', index: 1063 },
  { country: 'Liuzhou', emoji: '🇨🇳', index: 1064 },
  { country: 'Xuzhou', emoji: '🇨🇳', index: 1065 },
  { country: 'Zhuzhou', emoji: '🇨🇳', index: 1066 },
  { country: 'Jinzhou', emoji: '🇨🇳', index: 1067 },
  { country: 'Pizhou', emoji: '🇨🇳', index: 1068 },
  { country: 'Thrissur', emoji: '🇮🇳', index: 1069 },
  { country: 'Homs', emoji: '🇸🇾', index: 1070 },
  { country: 'St. Louis', emoji: '🇺🇸', index: 1071 },
  { country: 'Wixom', emoji: '🇺🇸', index: 1072 },
  { country: 'Illinois', emoji: '🇺🇸', index: 1073 },
  { country: 'Minsk', emoji: '🇧🇾', index: 1074 },
  { country: 'Urumqi', emoji: '🇨🇳', index: 1075 },
  { country: 'Wuxi', emoji: '🇨🇳', index: 1076 },
  { country: 'Jilin', emoji: '🇨🇳', index: 1077 },
  { country: 'Yiwu', emoji: '🇨🇳', index: 1078 },
  { country: 'Zunyi', emoji: '🇨🇳', index: 1079 },
  { country: 'Quito', emoji: '🇪🇨', index: 1080 },
  { country: 'Tiruppur', emoji: '🇮🇳', index: 1081 },
  { country: 'Turin', emoji: '🇮🇹', index: 1082 },
  { country: 'Tripoli', emoji: '🇱🇾', index: 1083 },
  { country: 'Tunis', emoji: '🇹🇳', index: 1084 },
  { country: 'Izmir', emoji: '🇹🇷', index: 1085 },
  { country: 'Kosovo', emoji: '🇽🇰', index: 1086 },
  { country: 'Kokomo', emoji: '🇺🇸', index: 1087 },
  { country: 'Tokyo', emoji: '🇯🇵', index: 1088 },
  { country: 'Omsk', emoji: '🇷🇺', index: 1089 },
  { country: 'Lyon', emoji: '🇫🇷', index: 1090 },
  { country: 'Oslo', emoji: '🇳🇴', index: 1091 },
  { country: 'Mosul', emoji: '🇮🇶', index: 1092 },
  { country: 'Qom', emoji: '🇮🇷', index: 1093 },
  { country: 'Toronto', emoji: '🇨🇦', index: 1094 },
  { country: 'Ross', emoji: '🇺🇸', index: 1095 },
  { country: 'Uyo', emoji: '🇳🇬', index: 1096 },
  { country: 'Porto', emoji: '🇵🇹', index: 1097 },
];

export { countryData };
